-- DDL generated by Postico 1.5.14
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE coffees (
    id SERIAL PRIMARY KEY,
    title text NOT NULL,
    description text,
    coffee_group text,
    create_at text NOT NULL DEFAULT current_timestamp,
    update_at text NOT NULL DEFAULT current_timestamp
);
